[package]
name = "flow_utils"
version = "0.2.0"
authors = ["TRACIP SAS <contact@tracip.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
